// Code generated by generator - dev. DO NOT EDIT.

package api

import (
	"context"
	"fmt"
	"strconv"
)

// execute runs awesomeOp.validate, and awesomeOp.handle in sequence.
func (op *awesomeOp) execute(ctx context.Context, request Request) (Response, error) {
	v0, v1 := op.validate(ctx, request)
	if v1 != nil {
		return Response{}, fmt.Errorf("validate: %w", v1)
	}

	v2, v3 := op.handle(ctx, v0)
	if v3 != nil {
		return Response{}, fmt.Errorf("handle: %w", v3)
	}

	return v2, nil
}

type Service interface {
	Awesome(ctx context.Context, request Request) (Response, error)
}

type serviceImpl struct {
	awesomeOp *awesomeOp
}

func (s *serviceImpl) Awesome(ctx context.Context, request Request) (Response, error) {
	return s.awesomeOp.execute(ctx, request)
}

func newService() Service {
	impl := &serviceImpl{awesomeOp: &awesomeOp{}}
	return impl
}

var _ Service = (*serviceImpl)(nil)

// Unnamed variable used to ensure `import "strconv"` is generated, as it is required below.
var _ = strconv.FormatInt(0, 10)

// --- Code generated by go run golang.org/x/tools/cmd/stringer@latest -type Status -linecomment -output /dev/stdout

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[StatusUnavailable-0]
	_ = x[StatusAvailable-1]
}

const _Status_name = "unavailableavailable"

var _Status_index = [...]uint8{0, 11, 20}

func (i Status) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_Status_index)-1 {
		return "Status(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Status_name[_Status_index[idx]:_Status_index[idx+1]]
}

// --- End code generated by go run golang.org/x/tools/cmd/stringer@latest -type Status -linecomment -output /dev/stdout
